export const FILL_BRIEF_INTRO = "FILL_BRIEF_INTRO";
export const FILL_LOCATION = "FILL_LOCATION";
export const SELECT_TIME = "SELECT_TIME";
export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const FILL_DESCRIPTION = "FILL_DESCRIPTION";
export const SELECT_PICTURE = "SELECT_PICTURE";
export const FILL_CONTACT = "FILL_CONTACT";
